# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' DR statistic (Rcpp version)
#'
#' Computes the Jetz DR rate
#'
#' @param x an ape::phylo object
#'
#' @return vector of rates for each tip
#' @export
#' @examples
#' tree <- ape::rcoal(1000)
#' DR_statistic_C(tree)
DR_statistic_C <- function(x) {
    .Call(`_fastdivrate_DR_statistic_C`, x)
}

#' DR statistic with sampling times
#'
#' Computes the Jetz DR rate, but sample at certain times in the psat
#'
#' @param x an ape::phylo object
#' @param sample_times a vector of ages
#'
#' @return matrix of rates for each tip, by sample time
#' @export
DR_statistic_time <- function(x, sample_times) {
    .Call(`_fastdivrate_DR_statistic_time`, x, sample_times)
}

#' Interval node statistic, with sampling times
#'
#' Computes the interval node statistic, sampling at certain times in the psat
#'
#' @param x an ape::phylo object
#' @param sample_times a vector of ages
#'
#' @return matrix of rates for each tip, by sample time
#' @export
interval_node_statistic <- function(x, sample_times) {
    .Call(`_fastdivrate_interval_node_statistic`, x, sample_times)
}

